<?php

namespace PollBundle\Repository;

/**
 * SubmittingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmittingRepository extends \Doctrine\ORM\EntityRepository
{
}
